### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [1zc/SM-Discord-Chat#1]
`[SM] Listing 18 plugins:
  01 "Admin File Reader" (1.10.0.6528) by AlliedModders LLC
  02 "Admin Help" (1.10.0.6528) by AlliedModders LLC
  03 "Admin Menu" (1.10.0.6528) by AlliedModders LLC
  04 "Anti-Flood" (1.10.0.6528) by AlliedModders LLC
  05 "Basic Ban Commands" (1.10.0.6528) by AlliedModders LLC
  06 "Basic Chat" (1.10.0.6528) by AlliedModders LLC
  07 "Basic Comm Control" (1.10.0.6528) by AlliedModders LLC
  08 "Basic Commands" (1.10.0.6528) by AlliedModders LLC
  09 "Basic Info Triggers" (1.10.0.6528) by AlliedModders LLC
  10 "Basic Votes" (1.10.0.6528) by AlliedModders LLC
  11 "Client Preferences" (1.10.0.6528) by AlliedModders LLC
  12 "Fun Commands" (1.10.0.6528) by AlliedModders LLC
  13 "Fun Votes" (1.10.0.6528) by AlliedModders LLC
  14 <Failed> "Infra's Simple Discord Chat Relay" (1.0.0) by Infra
  15 "Nextmap" (1.10.0.6528) by AlliedModders LLC
  16 "Player Commands" (1.10.0.6528) by AlliedModders LLC
  17 "Reserved Slots" (1.10.0.6528) by AlliedModders LLC
  18 "Sound Commands" (1.10.0.6528) by AlliedModders LLC
Errors:
Infra-DiscordChat.smx (Infra's Simple Discord Chat Relay): Required extension "SMJansson" file("smjansson.ext") not running`

**Comment by dhd555** [comment]
reason "VAC authentication error"
