### ISSUE TITLE
Plugin won't load due to the error below

### ISSUE THREAD

**Issue by KekkyShmekky** [1zc/SM-Discord-Chat#3]
[SM] Unable to load plugin "Infra-DiscordChat.smx": Native "DiscordWebHook.Send" was not found

Not sure how to solve this exactly if that's something server owners are able to do.

I have set my webhook URL accordingly in the config file provided.

**Comment by altxn** [comment]
You need Discord API Plugin installed as well for this to work.

https://forums.alliedmods.net/showthread.php?t=292448

**Comment by KekkyShmekky** [comment]
I actually already installed that and the error still occurs

**Comment by Kikio229** [comment]
i have this error too,

**Comment by 1zc** [comment]
#4
