### ISSUE TITLE
Log Infra Discord Chat

### ISSUE THREAD

**Issue by AsphyxiaAC** [1zc/SM-Discord-Chat#5]
I have been using it for 1 year in L4D2. It works 100%, but I have been receiving this for a few days now, can you fix it?

[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429
[Infra-DCR] ERROR: Failed to reach SteamAPI. Status: 429

**Comment by 1zc** [comment]
> HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

Something from your IP is hitting the SteamAPI way too many times and thus getting rate limited, not much I can help with on my end apart from maybe recommending you use the **Simple Style** webhook: https://github.com/1zc/SM-Discord-Chat#webhook-styles
